name: Tests CI

# Controls when the workflow will run
on: [push, workflow_dispatch]

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  static-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint

  static-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run typecheck

  unit-integration-vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install

      - name: Run Vitest
      - run: npm test

  e2e-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        uses: actions/setup-node@v1
          with:
            node-version: "16"
      - run: npm install

      - name: Run app
      - run: npm run dev

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          wait-on: "http://localhost:3000"
        env:
          PORT: "3000"
